# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-18 04:26
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20160502_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textblock',
            name='lesson',
            field=tinymce.models.HTMLField(),
        ),
    ]
