# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-18 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20190417_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textblock',
            name='lesson',
            field=models.TextField(),
        ),
    ]
